name: Tự động đồng bộ sang Repo Vercel

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy code mới nhất từ repo chính
        uses: actions/checkout@v4 # Đã nâng cấp lên v4 để sửa cảnh báo vàng
        with:
          fetch-depth: 0

      - name: Đẩy code sang Repo leaselinkconnect
        run: |
          git remote add vercel-repo https://${{ secrets.SYNC_TOKEN }}@github.com/chishiya2309/leaselinkconnect.git
          
          # Đã thêm --force để ép ghi đè repo phụ bằng code của repo chính
          git push vercel-repo main --force
